# Generated by Django 4.2 on 2023-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('food_relation', models.CharField(choices=[('CHEF', 'Chef'), ('NUTRITIONIST', 'Nutritionist'), ('PASTRY_CHEF', 'Pastry Chef'), ('FOOD_STYLIST', 'Food Stylist'), ('CULINARY_INSTRUCTOR', 'Culinary Instructor'), ('FOOD_CRITIC', 'Food Critic'), ('HOME_COOK', 'Home Cook'), ('OTHER', 'Other')], default='HOME_COOK', max_length=30)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
