# Generated by Django 3.2.18 on 2023-04-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(max_length=2)),
                ('unit', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('step_number', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('APPETIZERS', 'Apperizers'), ('BREAKFAST', 'Breakfast'), ('MAIN_DISHES', 'Main Dishes'), ('DESSERTS', 'Desserts'), ('SALLADS', 'Sallads'), ('SIDE_DISHES', 'Side Dishes'), ('SNACKS', 'Snacks'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Private'), (1, 'Public')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_post', to='cookbook.user')),
                ('ingredients', models.ManyToManyField(to='cookbook.Ingredient')),
                ('instructions', models.ManyToManyField(to='cookbook.Instruction')),
                ('likes', models.ManyToManyField(related_name='recipe_likes', to='cookbook.User')),
            ],
        ),
    ]
