# Generated by Django 3.2.18 on 2023-04-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
