# Generated by Django 3.2.18 on 2023-04-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_rename_user_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='c',
        ),
    ]
