# Generated by Django 3.2.18 on 2023-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_auto_20230413_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('APPETIZERS', 'Appetizers'), ('BREAKFAST', 'Breakfast'), ('MAIN_DISHES', 'Main Dishes'), ('DESSERTS', 'Desserts'), ('SALLADS', 'Sallads'), ('SIDE_DISHES', 'Side Dishes'), ('SNACKS', 'Snacks'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
