# Generated by Django 3.2.18 on 2023-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='excerp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
