# Generated by Django 3.2.18 on 2023-04-14 13:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0015_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
